// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A service inquiry AI agent.
 *
 * - serviceInquiry - A function that handles the service inquiry process.
 * - ServiceInquiryInput - The input type for the serviceInquiry function.
 * - ServiceInquiryOutput - The return type for the serviceInquiry function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ServiceInquiryInputSchema = z.object({
  query: z.string().describe('The service inquiry query from the user.'),
});
export type ServiceInquiryInput = z.infer<typeof ServiceInquiryInputSchema>;

const ServiceInquiryOutputSchema = z.object({
  answer: z.string().describe('The answer to the service inquiry.'),
});
export type ServiceInquiryOutput = z.infer<typeof ServiceInquiryOutputSchema>;

export async function serviceInquiry(input: ServiceInquiryInput): Promise<ServiceInquiryOutput> {
  return serviceInquiryFlow(input);
}

const prompt = ai.definePrompt({
  name: 'serviceInquiryPrompt',
  input: {schema: ServiceInquiryInputSchema},
  output: {schema: ServiceInquiryOutputSchema},
  prompt: `You are a customer service representative for Gulshan eBank.

  Answer the following question about bank services and policies:

  {{query}}
  `,
});

const serviceInquiryFlow = ai.defineFlow(
  {
    name: 'serviceInquiryFlow',
    inputSchema: ServiceInquiryInputSchema,
    outputSchema: ServiceInquiryOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
